//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy001.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Order
    {
        public int Id { get; set; }
        public int ProductId { get; set; }
        [DisplayName("Ürün Adedi")]
        public int ProductNumber { get; set; }
        public string Status { get; set; }
    
        public virtual Product Product { get; set; }

    }
}
