//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseStudy001.Models
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web.Mvc;

    public partial class Product
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int Id { get; set; }
        [DisplayName("Ürün")]
        public string ProductName { get; set; }
        [DisplayName("Marka")]
        public string TradeMark { get; set; }
        [DisplayName("Renk")]
        public string Color { get; set; }
        [DisplayName("Beden")]
        public string Size { get; set; }

        public List<Product> listProduct
        {
            get;
            set;
        }

        public IEnumerable<SelectListItem> ProductListItems
        {
            get
            {
                return new SelectList(listProduct, "Id", "ProductName");
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
